### ISSUE TITLE
Fix duplicate cloudtrail

### ISSUE THREAD

**Issue by limed** [mozilla-itcloud/maintenance-project#35]
Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1476728

Currently the following accounts

314563910040 akamai-aws
589768463761 nubis-market
633020870034 mozilla-netops
177680776199 nubis-lab

each have duplicate multi-region CloudTrails setup. Each account has one in us-east-1 and one in us-west-2

Please change the nubis config in these accounts so that only one Trail is configured (e.g. either in us-west-2 or us-east-1 but not both) to prevent duplication of SNS notifications and S3 files

**Comment by gozer** [comment]
All done
