### ISSUE TITLE
Remove Phonebook app deployment from appsvcs-generic

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/maintenance-project#5]
Copied from https://github.com/mozilla-itcloud/scl3-migration-project/issues/9

**Comment by gozer** [comment]
- [ ] Destroy phonebook prod deployment
- [ ] Destroy phonebook stage deployment
- [ ] Remove phonebook from appscvs-generic deployment configuration

**Comment by gozer** [comment]
Done
